services:
  nextjs:
    image: vuvuvuvvv/dhtverificationmanagement-nextjs:latest
    # build:
    #   context: ./nextjs-verification-management
    #   dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./nextjs-verification-management/.env.local
    environment:
      NEXT_PUBLIC_API_URL: 'http://192.168.1.204:5000/api'
      NEXT_PUBLIC_URL: 'http://192.168.1.204:3000'
    depends_on:
      - flask
    networks:
      - next-flask

  flask:
    image: vuvuvuvvv/dhtverificationmanagement-flask:latest
    # build:
    #   context: ./flask-verification-management
    #   dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./flask-verification-management/.env
    environment:
      # FLASK_ENV: development
      SECRET_KEY: '205062'
      DATABASE_URL: 'postgresql://postgres:205062@postgres:5432/verification_management'
      JWT_SECRET_KEY: '205062'
      CLIENT_BASE_URL: 'http://192.168.1.204:3000'
      COMPANY_NAME: 'DHT Company'
      SENDER_NAME: 'DHT no-reply'
      ADMIN_MAIL: 'smtpbotnoreply@gmail.com'
      ADMIN_TEL: '19006868'
      SENDER_MAIL: 'smtpbotnoreply@gmail.com'
      MAIL_USERNAME: 'smtpbotnoreply@gmail.com'
      MAIL_PASSWORD: 'hlgumagnwrotjgad'
    depends_on:
      - postgres
    networks:
      - next-flask
      - flask-db

  postgres:
    image: dhtverificationmanagement-postgres:latest
    # image: postgres:latest
    environment:
      POSTGRES_DB: verification_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 205062
    ports:
      - "5432:5432"
    networks:
      - flask-db
    volumes:
      # - pgdata:/var/lib/postgresql/data
      - F:\PostgreSQL\16\data-docker-backup:/var/lib/postgresql/data

# volumes:
#   pgdata:
#     driver: local

networks:
  next-flask:
  flask-db: